global:
  scrape_interval: 5s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "ml_api"
    static_configs:
      - targets: ["model-api:5000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]